### ISSUE TITLE
Select and copy output

### ISSUE THREAD

**Issue by janosimas** [31i73/atom-output-panel#1]
Hi,
It would be great to be able to select and copy the text from the output.

**Comment by Positive07** [comment]
The problem is that panels and UI in Atom have disabled selection.

The solution is rather easy, you should add [`user-select`](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select) to the style of the objects you want to make selectionable (probably the body or xterm itself).
```less
-webkit-user-select: text;
user-select: text;
```
